"""Urdu Nastaliq ASS and SRT Subtitle Generator.

Builds Advanced SubStation Alpha (.ass) subtitle scripts optimized for
vertical 9:16 Instagram Reels (1080x1920) with authentic Nastaliq calligraphy,
RTL formatting, drop shadows, and word-level kinetic highlight karaoke tags.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from app.services.tts.provider import WordTimestamp


@dataclass
class SubtitleVerse:
    """Urdu poetry verse with timing information."""

    text: str
    start_time: float
    end_time: float
    words: list[WordTimestamp] | None = None


def format_ass_time(seconds: float) -> str:
    """Formats seconds into ASS timestamp format: H:MM:SS.cc (centiseconds)."""
    if seconds < 0:
        seconds = 0.0
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis >= 100:
        centis = 99
    return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"


def format_srt_time(seconds: float) -> str:
    """Formats seconds into SRT timestamp format: HH:MM:SS,mmm (milliseconds)."""
    if seconds < 0:
        seconds = 0.0
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int(round((seconds - int(seconds)) * 1000))
    if millis >= 1000:
        millis = 999
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


class ASSSubtitleBuilder:
    """Generates styled ASS subtitle scripts for vertical 9:16 Reels."""

    def __init__(
        self,
        font_name: str = "Noto Nastaliq Urdu",
        font_size: int = 60,
        primary_color_bgr: str = "00FFFFFF",  # White in &HAABBGGRR
        highlight_color_bgr: str = "000B9EF5",  # Gold #F59E0B in BGR
        outline_color_bgr: str = "00100B08",  # Deep Dark #080B10
        back_color_bgr: str = "80000000",  # Semi-transparent shadow
        resolution_x: int = 1080,
        resolution_y: int = 1920,
    ) -> None:
        self.font_name = font_name
        self.font_size = font_size
        self.primary_color = primary_color_bgr
        self.highlight_color = highlight_color_bgr
        self.outline_color = outline_color_bgr
        self.back_color = back_color_bgr
        self.res_x = resolution_x
        self.res_y = resolution_y

    def build_header(self, title: str = "AlfaazStudio Reel") -> str:
        """Constructs ASS script info and style headers."""
        header = f"""[Script Info]
; Script generated by AlfaazStudio (الفاظ اسٹوڈیو)
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: {self.res_x}
PlayResY: {self.res_y}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Nastaliq_Main,{self.font_name},{self.font_size},&H{self.primary_color},&H{self.highlight_color},&H{self.outline_color},&H{self.back_color},-1,0,0,0,100,100,0,0,1,3.5,2.0,2,80,80,320,1
Style: Nastaliq_Title,{self.font_name},44,&H{self.highlight_color},&H{self.primary_color},&H{self.outline_color},&H{self.back_color},-1,0,0,0,100,100,0,0,1,2.5,1.5,8,60,60,180,1
Style: Nastaliq_Poet,{self.font_name},38,&H{self.primary_color},&H{self.highlight_color},&H{self.outline_color},&H{self.back_color},0,0,0,0,100,100,0,0,1,2.0,1.0,8,60,60,250,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        return header

    def build_ass_content(
        self,
        verses: Sequence[SubtitleVerse],
        title: str | None = None,
        poet_name: str | None = None,
        enable_karaoke: bool = True,
    ) -> str:
        """Assembles a complete ASS subtitle file content string."""
        content = self.build_header(title=title or "Urdu Poetry Reel")

        # Optional Title & Poet Name Header in top third (first 4 seconds)
        if title:
            start_t = format_ass_time(0.0)
            end_t = format_ass_time(min(4.0, verses[-1].end_time if verses else 4.0))
            content += (
                f"Dialogue: 0,{start_t},{end_t},Nastaliq_Title,,0,0,0,,{{\\fad(400,400)}}{title}\n"
            )

        if poet_name:
            start_t = format_ass_time(0.0)
            end_t = format_ass_time(min(4.0, verses[-1].end_time if verses else 4.0))
            content += f"Dialogue: 0,{start_t},{end_t},Nastaliq_Poet,,0,0,0,,{{\\fad(400,400)}}شاعر: {poet_name}\n"

        for verse in verses:
            start_t = format_ass_time(verse.start_time)
            end_t = format_ass_time(verse.end_time)

            if enable_karaoke and verse.words and len(verse.words) > 0:
                # Build karaoke tags: \k<duration_in_centiseconds>
                karaoke_parts: list[str] = []
                for word_info in verse.words:
                    word_duration = max(0.1, word_info.end_time - word_info.start_time)
                    centi = int(round(word_duration * 100))
                    karaoke_parts.append(f"{{\\k{centi}}}{word_info.word}")

                verse_text = " ".join(karaoke_parts)
                dialogue = f"Dialogue: 1,{start_t},{end_t},Nastaliq_Main,,0,0,0,,{{\\fad(200,200)}}{verse_text}\n"
            else:
                dialogue = f"Dialogue: 1,{start_t},{end_t},Nastaliq_Main,,0,0,0,,{{\\fad(250,250)}}{verse.text}\n"

            content += dialogue

        return content

    def write_ass_file(
        self,
        output_path: Path,
        verses: Sequence[SubtitleVerse],
        title: str | None = None,
        poet_name: str | None = None,
        enable_karaoke: bool = True,
    ) -> Path:
        """Writes ASS content to disk at the target path."""
        content = self.build_ass_content(
            verses=verses,
            title=title,
            poet_name=poet_name,
            enable_karaoke=enable_karaoke,
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        return output_path


def generate_srt_content(verses: Sequence[SubtitleVerse]) -> str:
    """Generates standard SRT subtitles for external players."""
    lines: list[str] = []
    for idx, verse in enumerate(verses, start=1):
        lines.append(str(idx))
        lines.append(f"{format_srt_time(verse.start_time)} --> {format_srt_time(verse.end_time)}")
        lines.append(verse.text)
        lines.append("")
    return "\n".join(lines)

